
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CHAVE_DIR CHAVE_ESQ DOIS_PONTOS ID KW_CRUZAMENTO KW_DE KW_DUPLA KW_EM KW_MAO KW_PARA KW_RUA KW_SINAL KW_TAMANHO KW_UNICA KW_VERDE KW_VERMELHO MEDIDA_M PONTO_VIRGULA STRING TEMPO_S string_mf variavel_mfprograma : declaracao_listadeclaracao_lista : declaracao_lista declaracaodeclaracao_lista : declaracaodeclaracao : decl_sinal_global\n| decl_rua\n| decl_cruzamentocorpo_sinal : CHAVE_ESQ KW_VERDE DOIS_PONTOS TEMPO_S PONTO_VIRGULA KW_VERMELHO DOIS_PONTOS TEMPO_S PONTO_VIRGULA CHAVE_DIRdecl_sinal_global : KW_SINAL ID corpo_sinaldecl_rua : KW_RUA STRING CHAVE_ESQ rua_item_lista CHAVE_DIRrua_item_lista : rua_item_lista rua_itemrua_item_lista : rua_itemrua_item : rua_tamanho\n| rua_mao\n| rua_sinal_ref\n| rua_sinal_inlinerua_tamanho : KW_TAMANHO DOIS_PONTOS MEDIDA_M PONTO_VIRGULArua_mao : KW_MAO DOIS_PONTOS mao_valor PONTO_VIRGULAmao_valor : KW_DUPLAmao_valor : KW_UNICArua_sinal_ref : KW_SINAL KW_EM MEDIDA_M ID PONTO_VIRGULArua_sinal_inline : KW_SINAL KW_EM MEDIDA_M corpo_sinaldecl_cruzamento : KW_CRUZAMENTO CHAVE_ESQ cruzamento_item_lista CHAVE_DIRcruzamento_item_lista : cruzamento_item_lista cruzamento_itemcruzamento_item_lista : cruzamento_itemcruzamento_item : cruzamento_entrada\n| cruzamento_par_simples\n| cruzamento_par_com_corpo\n| cruzamento_sinal_ref\n| cruzamento_sinal_inlinecruzamento_entrada : STRING KW_EM MEDIDA_M PONTO_VIRGULAcruzamento_sinal_ref : KW_SINAL ID PONTO_VIRGULAcruzamento_sinal_inline : KW_SINAL corpo_sinalcruzamento_par_simples : KW_DE STRING KW_PARA STRING PONTO_VIRGULAcruzamento_par_com_corpo : KW_DE STRING KW_PARA STRING CHAVE_ESQ par_sinal CHAVE_DIRpar_sinal : KW_SINAL ID PONTO_VIRGULApar_sinal : KW_SINAL corpo_sinal'
    
_lr_action_items = {'KW_SINAL':([0,2,3,4,5,6,10,13,14,16,17,18,19,20,21,22,23,28,29,30,31,32,33,37,38,42,44,45,51,58,61,62,64,65,66,68,72,78,],[7,7,-3,-4,-5,-6,-2,26,-8,36,26,-24,-25,-26,-27,-28,-29,36,-11,-12,-13,-14,-15,-22,-23,-32,-9,-10,-31,-30,-16,-17,-21,-33,70,-20,-34,-7,]),'KW_RUA':([0,2,3,4,5,6,10,14,37,44,78,],[8,8,-3,-4,-5,-6,-2,-8,-22,-9,-7,]),'KW_CRUZAMENTO':([0,2,3,4,5,6,10,14,37,44,78,],[9,9,-3,-4,-5,-6,-2,-8,-22,-9,-7,]),'$end':([1,2,3,4,5,6,10,14,37,44,78,],[0,-1,-3,-4,-5,-6,-2,-8,-22,-9,-7,]),'ID':([7,26,57,70,],[11,41,63,73,]),'STRING':([8,13,17,18,19,20,21,22,23,25,38,42,50,51,58,65,72,78,],[12,24,24,-24,-25,-26,-27,-28,-29,40,-23,-32,59,-31,-30,-33,-34,-7,]),'CHAVE_ESQ':([9,11,12,26,57,59,70,],[13,15,16,15,15,66,15,]),'KW_DE':([13,17,18,19,20,21,22,23,38,42,51,58,65,72,78,],[25,25,-24,-25,-26,-27,-28,-29,-23,-32,-31,-30,-33,-34,-7,]),'KW_VERDE':([15,],[27,]),'KW_TAMANHO':([16,28,29,30,31,32,33,45,61,62,64,68,78,],[34,34,-11,-12,-13,-14,-15,-10,-16,-17,-21,-20,-7,]),'KW_MAO':([16,28,29,30,31,32,33,45,61,62,64,68,78,],[35,35,-11,-12,-13,-14,-15,-10,-16,-17,-21,-20,-7,]),'CHAVE_DIR':([17,18,19,20,21,22,23,28,29,30,31,32,33,38,42,45,51,58,61,62,64,65,68,69,72,74,76,77,78,],[37,-24,-25,-26,-27,-28,-29,44,-11,-12,-13,-14,-15,-23,-32,-10,-31,-30,-16,-17,-21,-33,-20,72,-34,-36,-35,78,-7,]),'KW_EM':([24,36,],[39,48,]),'DOIS_PONTOS':([27,34,35,67,],[43,46,47,71,]),'MEDIDA_M':([39,46,48,],[49,53,57,]),'KW_PARA':([40,],[50,]),'PONTO_VIRGULA':([41,49,52,53,54,55,56,59,63,73,75,],[51,58,60,61,62,-18,-19,65,68,76,77,]),'TEMPO_S':([43,71,],[52,75,]),'KW_DUPLA':([47,],[55,]),'KW_UNICA':([47,],[56,]),'KW_VERMELHO':([60,],[67,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'declaracao_lista':([0,],[2,]),'declaracao':([0,2,],[3,10,]),'decl_sinal_global':([0,2,],[4,4,]),'decl_rua':([0,2,],[5,5,]),'decl_cruzamento':([0,2,],[6,6,]),'corpo_sinal':([11,26,57,70,],[14,42,64,74,]),'cruzamento_item_lista':([13,],[17,]),'cruzamento_item':([13,17,],[18,38,]),'cruzamento_entrada':([13,17,],[19,19,]),'cruzamento_par_simples':([13,17,],[20,20,]),'cruzamento_par_com_corpo':([13,17,],[21,21,]),'cruzamento_sinal_ref':([13,17,],[22,22,]),'cruzamento_sinal_inline':([13,17,],[23,23,]),'rua_item_lista':([16,],[28,]),'rua_item':([16,28,],[29,45,]),'rua_tamanho':([16,28,],[30,30,]),'rua_mao':([16,28,],[31,31,]),'rua_sinal_ref':([16,28,],[32,32,]),'rua_sinal_inline':([16,28,],[33,33,]),'mao_valor':([47,],[54,]),'par_sinal':([66,],[69,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> declaracao_lista','programa',1,'p_programa','analisador_sintatico.py',9),
  ('declaracao_lista -> declaracao_lista declaracao','declaracao_lista',2,'p_declaracao_lista_multi','analisador_sintatico.py',13),
  ('declaracao_lista -> declaracao','declaracao_lista',1,'p_declaracao_lista_um','analisador_sintatico.py',17),
  ('declaracao -> decl_sinal_global','declaracao',1,'p_declaracao','analisador_sintatico.py',21),
  ('declaracao -> decl_rua','declaracao',1,'p_declaracao','analisador_sintatico.py',22),
  ('declaracao -> decl_cruzamento','declaracao',1,'p_declaracao','analisador_sintatico.py',23),
  ('corpo_sinal -> CHAVE_ESQ KW_VERDE DOIS_PONTOS TEMPO_S PONTO_VIRGULA KW_VERMELHO DOIS_PONTOS TEMPO_S PONTO_VIRGULA CHAVE_DIR','corpo_sinal',10,'p_corpo_sinal','analisador_sintatico.py',31),
  ('decl_sinal_global -> KW_SINAL ID corpo_sinal','decl_sinal_global',3,'p_decl_sinal_global','analisador_sintatico.py',39),
  ('decl_rua -> KW_RUA STRING CHAVE_ESQ rua_item_lista CHAVE_DIR','decl_rua',5,'p_decl_rua','analisador_sintatico.py',47),
  ('rua_item_lista -> rua_item_lista rua_item','rua_item_lista',2,'p_rua_item_lista_multi','analisador_sintatico.py',51),
  ('rua_item_lista -> rua_item','rua_item_lista',1,'p_rua_item_lista_um','analisador_sintatico.py',55),
  ('rua_item -> rua_tamanho','rua_item',1,'p_rua_item','analisador_sintatico.py',59),
  ('rua_item -> rua_mao','rua_item',1,'p_rua_item','analisador_sintatico.py',60),
  ('rua_item -> rua_sinal_ref','rua_item',1,'p_rua_item','analisador_sintatico.py',61),
  ('rua_item -> rua_sinal_inline','rua_item',1,'p_rua_item','analisador_sintatico.py',62),
  ('rua_tamanho -> KW_TAMANHO DOIS_PONTOS MEDIDA_M PONTO_VIRGULA','rua_tamanho',4,'p_rua_tamanho','analisador_sintatico.py',66),
  ('rua_mao -> KW_MAO DOIS_PONTOS mao_valor PONTO_VIRGULA','rua_mao',4,'p_rua_mao','analisador_sintatico.py',70),
  ('mao_valor -> KW_DUPLA','mao_valor',1,'p_mao_dupla','analisador_sintatico.py',74),
  ('mao_valor -> KW_UNICA','mao_valor',1,'p_mao_unica','analisador_sintatico.py',78),
  ('rua_sinal_ref -> KW_SINAL KW_EM MEDIDA_M ID PONTO_VIRGULA','rua_sinal_ref',5,'p_rua_sinal_ref','analisador_sintatico.py',83),
  ('rua_sinal_inline -> KW_SINAL KW_EM MEDIDA_M corpo_sinal','rua_sinal_inline',4,'p_rua_sinal_inline','analisador_sintatico.py',88),
  ('decl_cruzamento -> KW_CRUZAMENTO CHAVE_ESQ cruzamento_item_lista CHAVE_DIR','decl_cruzamento',4,'p_decl_cruzamento','analisador_sintatico.py',96),
  ('cruzamento_item_lista -> cruzamento_item_lista cruzamento_item','cruzamento_item_lista',2,'p_cruzamento_item_lista_multi','analisador_sintatico.py',100),
  ('cruzamento_item_lista -> cruzamento_item','cruzamento_item_lista',1,'p_cruzamento_item_lista_um','analisador_sintatico.py',104),
  ('cruzamento_item -> cruzamento_entrada','cruzamento_item',1,'p_cruzamento_item','analisador_sintatico.py',108),
  ('cruzamento_item -> cruzamento_par_simples','cruzamento_item',1,'p_cruzamento_item','analisador_sintatico.py',109),
  ('cruzamento_item -> cruzamento_par_com_corpo','cruzamento_item',1,'p_cruzamento_item','analisador_sintatico.py',110),
  ('cruzamento_item -> cruzamento_sinal_ref','cruzamento_item',1,'p_cruzamento_item','analisador_sintatico.py',111),
  ('cruzamento_item -> cruzamento_sinal_inline','cruzamento_item',1,'p_cruzamento_item','analisador_sintatico.py',112),
  ('cruzamento_entrada -> STRING KW_EM MEDIDA_M PONTO_VIRGULA','cruzamento_entrada',4,'p_cruzamento_entrada','analisador_sintatico.py',117),
  ('cruzamento_sinal_ref -> KW_SINAL ID PONTO_VIRGULA','cruzamento_sinal_ref',3,'p_cruzamento_sinal_ref','analisador_sintatico.py',122),
  ('cruzamento_sinal_inline -> KW_SINAL corpo_sinal','cruzamento_sinal_inline',2,'p_cruzamento_sinal_inline','analisador_sintatico.py',127),
  ('cruzamento_par_simples -> KW_DE STRING KW_PARA STRING PONTO_VIRGULA','cruzamento_par_simples',5,'p_cruzamento_par_simples','analisador_sintatico.py',136),
  ('cruzamento_par_com_corpo -> KW_DE STRING KW_PARA STRING CHAVE_ESQ par_sinal CHAVE_DIR','cruzamento_par_com_corpo',7,'p_cruzamento_par_com_corpo','analisador_sintatico.py',141),
  ('par_sinal -> KW_SINAL ID PONTO_VIRGULA','par_sinal',3,'p_par_sinal_ref','analisador_sintatico.py',146),
  ('par_sinal -> KW_SINAL corpo_sinal','par_sinal',2,'p_par_sinal_inline','analisador_sintatico.py',151),
]
